name       : ktnef
version    : 23.04.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/ktnef-23.04.2.tar.xz : dad17abcaabd4f7556286dea82f00f7cb4d754e7e6031629d5d5f2faa06136e8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
