name       : ktnef
version    : 18.12.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/ktnef-18.12.0.tar.xz : 8b658a74ed994740ce358356a60f2a0333068adf3e64cddcf333c162d47b49b1
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
