name       : ktnef
version    : 21.08.2
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/ktnef-21.08.2.tar.xz : 17e3e588b3af2bb80f82d85f41e58ffaab9bd5174116820d957854e1d0788416
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
