name       : ktnef
version    : 20.08.3
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/ktnef-20.08.3.tar.xz : a406de0492b97ca7e9454e79286db14f97be8d68c7f928439a4294e8b11e49d2
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
