name       : ktnef
version    : 22.04.2
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/ktnef-22.04.2.tar.xz : ffc242379d34679b65f0053e2790486d6d32615648358be97d9f65a6ed5c9b7a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
