name       : ktnef
version    : 21.12.3
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/ktnef-21.12.3.tar.xz : d496cc88668646b9b4c13a07de26e1e82bd5dec973737001717d52856c48c9c6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
