name       : ktnef
version    : 20.12.1
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/ktnef-20.12.1.tar.xz : cd9155107c2358d0c03ffdd22d9eeba6931ab9cbb9481e05ed97be0397aa04df
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
