name       : ktnef
version    : 19.08.1
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/ktnef-19.08.1.tar.xz : bab23e40af2fe5ba2dd0be71687fbdd56d0868f2ef2a399721da88b12c65764f
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
