name       : ktnef
version    : 20.08.1
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/ktnef-20.08.1.tar.xz : 433b232a0c835e7f27c06e6d19856e4f8690c3e3b5c5d63f85172897b2448c81
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
