name       : ktnef
version    : 21.12.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/ktnef-21.12.0.tar.xz : 08e6565ba81d93154f8fca8f500c1570e357c28b48997713d3f519eaaafc650d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
