name       : ktnef
version    : 19.12.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/ktnef-19.12.0.tar.xz : ae294f943788222d5abb264c1a7805222bdedf558e5f0466d1fd9926486e96df
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
