name       : ktnef
version    : 21.08.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/ktnef-21.08.0.tar.xz : d47ca164216d39cb3520b66aaddf7127c5a424d3b848b9ac62131b9fd71de07e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
