name       : ktnef
version    : 17.08.2
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/ktnef-17.08.2.tar.xz : ed841a071013b21775378ff961b52934c0b9ab1502420df8c1340689750f4c04
license    : LGPL-2.1
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
