name       : ktnef
version    : 20.12.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/ktnef-20.12.3.tar.xz : 78d7f3d512a1ab1d7ef4af81b47a865e933b2338004ddb174d35913f13887873
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
