name       : ktnef
version    : 22.04.1
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/ktnef-22.04.1.tar.xz : 8938f4940ef6c65c67da761d1fe6e17bbcf36b37c4704bf6fff0f105258af6e6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
