name       : ktnef
version    : 21.04.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/ktnef-21.04.0.tar.xz : 1efda4eeeddad6cc7a12ebbc686f563849cbf2d75f3e7b58673d9f27965b407f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
