name       : ktnef
version    : 22.08.3
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/ktnef-22.08.3.tar.xz : bc51a28d1f542bcff25f327c8f39f49b090ffa626c14123b083d9af5ef4013ff
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
