name       : ktnef
version    : 21.08.3
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/ktnef-21.08.3.tar.xz : 0a6ff64449c9bc67560570572a3db21e7e699d357ee2a5351a65684812f2da6d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
