name       : ktnef
version    : 23.04.1
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/ktnef-23.04.1.tar.xz : 2b7e4b8530af0f4db42b6ded2d4728fe89d08807206c0fc6bc2033bb2e7c3756
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
