name       : ktnef
version    : 21.12.1
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/ktnef-21.12.1.tar.xz : 7ac7bdf6e7261ae09b621f1f563f746baf288d291c285c1cda97c200bb3d1447
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
