name       : ktnef
version    : 17.08.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/ktnef-17.08.3.tar.xz : 36ca5448c1e65e5a2794e1ab8154ae93ae11087f9e55c627ec50463bd6f2003a
license    : LGPL-2.1
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
