name       : ktnef
version    : 21.04.1
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/ktnef-21.04.1.tar.xz : 2e122470ec8c879d2faaf31ddbf60d82732d5f34304e305a3e97dfe91f80418b
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
