name       : ktnef
version    : 23.04.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/ktnef-23.04.0.tar.xz : 4adc253d58d47be7ec6488b120ae750c47e182975275ba2a94a051e88d446ba8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
