name       : ktnef
version    : 20.08.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/ktnef-20.08.0.tar.xz : 69d18a052cc522161821f98fb4103d38e1ff566622915b7138866e7737ffa62f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
