name       : ktnef
version    : 19.08.2
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/ktnef-19.08.2.tar.xz : d8efabe72eedd5e89f3de9637a1a6d68ce670ec071e031470aa6852f9ad8561d
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
