name       : ktnef
version    : 22.04.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/ktnef-22.04.3.tar.xz : 70dab3e8e10f6bf4458fa0f918c82efe829b4a692799b0816d383228a7527b5b
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
