name       : ktnef
version    : 18.08.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/ktnef-18.08.0.tar.xz : 11478cd48a02e591710a615df05ab0ad1d435fb1673bc241082897e86595ef00
license    : LGPL-2.1
component  : programming.library
summary    : API for handling TNEF data
description: |
    API for handling TNEF data.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
